### ISSUE TITLE
pxf make error (make test & make -C) 

### ISSUE THREAD

**Issue by kai76olla** [greenplum-db/pxf#927]
Hi,

I have an centos7 env with gpdb 6.23.0 running on it. 
Then I cloned the pxf code into the contrib folder under gpdb source code path. 
when I was trying to build pxf, I came across these errors:

$ make 
BUILD SUCCESSFUL

$ make test
[1674715619] Cmd Suite - 67/67 specs ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••• SUCCESS! 5.04176ms PASS
[1674715619] EndToEnd Suite - 5/5 specs ••••• SUCCESS! 16.486254ms PASS

Ginkgo ran 2 suites in 4.858285575s
Test Suite Passed
make[1]: Leaving directory `/home/gpadmin/workspace/pxf/cli/go/src/pxf-cli'
make -C server test
make[1]: Entering directory `/home/gpadmin/workspace/pxf/server'
./gradlew -Pversion=6.5.1-SNAPSHOT -PapiVersion=16 test

> Task :pxf-service:test

ProfilesConfTest > testMalformedXmlFile() FAILED
    org.opentest4j.AssertionFailedError at ProfilesConfTest.java:196

248 tests completed, 1 failed, 1 skipped

> Task :pxf-service:test FAILED

FAILURE: Build failed with an exception.

So I modified the java source "ProfilesConfTest.java" as below :

[gpadmin@mdw profile]$ pwd
/home/gpadmin/workspace/pxf-release-6.3.1/server/pxf-service/src/test/java/org/greenplum/pxf/service/profile
-----------
/*
    @Test
    public void testMalformedXmlFile() {
        Exception e = assertThrows(ProfileConfException.class,
                () -> getProfilesConf("malformedXmlFile"));
        assertTrue(e.getMessage().contains("Content is not allowed in prolog"));
    }
*/
-----------

And then build succeeded.
I have 2 question.

1) Is there any problem if I modify the source as above and use it?
2) If that doesn't work, can you fix that error?
ProfilesConfTest > testMalformedXmlFile() FAILED
    org.opentest4j.AssertionFailedError at ProfilesConfTest.java:196

248 tests completed, 1 failed, 1 skipped

Best Regards
Kai

**Comment by bradfordb-vmware** [comment]
I'm not able to reproduce the failing test (`ProfilesConfTest`) in my local dev environment and the test is passing in our CI for CentOS 7. Can you provide the output of `./gradlew -version` when run in `pxf/server` directory? The output should look something like

```console
------------------------------------------------------------
Gradle 6.8.2
------------------------------------------------------------

Build time:   2021-02-05 12:53:00 UTC
Revision:     b9bd4a5c6026ac52f690eaf2829ee26563cad426

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          1.8.0_331 (Oracle Corporation 25.331-b09)
OS:           Linux 6.0.0-6-amd64 amd64
````

**Comment by bradfordb-vmware** [comment]
I've looked into this issue some more, I think I know why this test is failing for you and not me.

The crux of the issue is that `ProfilesConfTest > testMalformedXmlFile` is failing because the test is asserting that an exception message contains a particular substring, however this particular substring comes from the JDK itself and changes based on the locale. When I change my locale to German (`export LC_ALL=de_DE.UTF-8`) and run the test, it fails because the message is localized to "Content ist nicht zulässig in Prolog." instead of "Content is not allowed in prolog." Note, that not every locale results in translation of the message; looking at https://github.com/openjdk/jdk8u/tree/master/jaxp/src/com/sun/org/apache/xerces/internal/impl/msg, it doesn't look like there is localization for Russian for example.

What is the output when you run `locale` on the system?

**Comment by kai76olla** [comment]
I reinstalled the os and tried compiling again.
It works fine now.

Before (build error)
Centos 7 Minimum installation

After (build successed)
Centos 7 Minimum installation
+ debugging tool + dev tool + compatibility library

My guess is that something went wrong with the compatibility library. 
thank you for your support~~
