### ISSUE TITLE
if we try to install pxf on offline, is it possible?

### ISSUE THREAD

**Issue by sm2jyh** [greenplum-db/pxf#957]
we are trying to install this on offline environment
is it possible?
and if it is possible, which thing we need to install

**Comment by bradfordb-vmware** [comment]
You should be able to install PXF on a machine that is offline. The RPM packages does not declare any dependencies, so installing with `rpm -i ./<path-to-PXF-RPM>` should work. It is assumed that PXF is being installed on a machine that also has Greenplum Database installed, along with all the dependencies need by GPDB. Additionally, you will need to have Java installed in order to run the PXF service.

The PXF CLI (e.g., `pxf cluster start`) assumes network connectivity among the GPDB machines.
